# Generated by Django 2.1.5 on 2019-03-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinput',
            name='Age',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='HospNumb',
            field=models.BigIntegerField(),
        ),
    ]
